### PR TITLE
Fixes #1026

### LINKED ISSUE #1026: [melodic][global_planner] Raw-pointers of class GlobalPlanner never initialized to null in default constructor
The raw pointers `p_calc_, planner_, path_maker_, orientation_filter_` of class GlobalPlanner are never initialized to nullptr during default construction, causing the check in the destructor to fail (and consequently causing a seg fault) if the planner was never initialized.

### PR DESCRIPTION
**Pull request by DLu**

### CODE REVIEW

File: global_planner/include/global_planner/planner_core.h [hunk 1]
```diff
@@ -193,7 +193,7 @@ class GlobalPlanner : public nav_core::BaseGlobalPlanner {
         int publish_scale_;
 
         void outlineMap(unsigned char* costarr, int nx, int ny, unsigned char value);
-        unsigned char* cost_array_;
```
Comment (DLu) [inline global_planner/include/global_planner/planner_core.h:196]: This is unused in the package.

**Review by mikeferguson — APPROVED** [review]

**Review by aaronhoy — APPROVED** [review]

File: global_planner/include/global_planner/planner_core.h (hunk 1 above)
Comment (kyrofa) [reply global_planner/include/global_planner/planner_core.h:196]: This seems like an unnecessary ABI break.
