### PR TITLE
fix crashes in AMCL

### LINKED ISSUE #1151: [amcl, move_base] crashed with malformed messages from laser sensor (/scan topic)
Hi, I have done some tests and found some bad crashes on amcl and move_base nodes. Here are the stderr outputs.

1. 
`amcl: /home/r1/ros1_clang_navigation/src/navigation/amcl/src/amcl/sensors/amcl_laser.cpp:290: static double amcl::AMCLLaser::LikelihoodFieldModel(amcl::AMCLLaserData *, pf_sample_set_t *): Assertion 'pz <= 1.0' failed
[amcl-1] process has died [pid 500397, exit code -6, cmd /home/r1/ros1_clang_navigation/devel/lib/amcl/amcl scan:=scan __name:=amcl __log:=/home/r1/.ros/log/bceaf65c-ee8d-11eb-8cea-fba906074cfc/amcl-1.log].
log file: /home/r1/.ros/log/bceaf65c-ee8d-11eb-8cea-fba906074cfc/amcl-1*.log
`

2.
`amcl: /home/r1/ros1_clang_navigation/src/navigation/amcl/src/amcl/sensors/amcl_laser.cpp:291: static double amcl::AMCLLaser::LikelihoodFieldModel(amcl::AMCLLaserData *, pf_sample_set_t *): Assertion 'pz >= 0.0' failed.
[amcl-1] process has died [pid 503464, exit code -6, cmd /home/r1/ros1_clang_navigation/devel/lib/amcl/amcl scan:=scan __name:=amcl __log:=/home/r1/.ros/log/bceaf65c-ee8d-11eb-8cea-fba906074cfc/amcl-1.log].
log file: /home/r1/.ros/log/bceaf65c-ee8d-11eb-8cea-fba906074cfc/amcl-1*.log`

3.
`terminate called after throwing an instance of 'std::runtime_error'
  what():  Duration is out of dual 32-bit range
[move_base-1] process has died [pid 498711, exit code -6, cmd /home/r1/ros1_clang_navigation/devel/lib/move_base/move_base cmd_vel:=/cmd_vel odom:=odom __name:=move_base __log:=/home/r1/.ros/log/bceaf65c-ee8d-11eb-8cea-fba906074cfc/move_base-1.log].
log file: /home/r1/.ros/log/bceaf65c-ee8d-11eb-8cea-fba906074cfc/move_base-1*.log
`

4.
`terminate called after throwing an instance of 'std::runtime_error'
  what():  Time is out of dual 32-bit range
[move_base-1] process has died [pid 499385, exit code -6, cmd /home/r1/ros1_clang_navigation/devel/lib/move_base/move_base cmd_vel:=/cmd_vel odom:=odom __name:=move_base __log:=/home/r1/.ros/log/bceaf65c-ee8d-11eb-8cea-fba906074cfc/move_base-1.log].
log file: /home/r1/.ros/log/bceaf65c-ee8d-11eb-8cea-fba906074cfc/move_base-1*.log
`

I try to figure out the causes but I'm not very sure.

- In move_base, sensor_msgs/LaserScan.msg:

std_msgs/Header header
float32 angle_min
float32 angle_max
float32 angle_increment
float32 time_increment      \#it seems the value is below zero or beyond INT_MAX, move_base will crash.
float32 scan_time
float32 range_min
float32 range_max
float32[] ranges
float32[] intensities

- In amcl, navigation/amcl/src/amcl/sensors/amcl_laser.cpp:290:
`assert(pz <= 1.0);`
 `assert(pz >= 0.0);`
The two asserts disallow strange inputs but they just crash the node. Maybe just discarding the message is a more graceful way?

### PR DESCRIPTION
**Pull request by easylyou**
fix #1151 about move_base crashes.

if the LaserScan.msg is malformed, the move_base will crash.
sensor_msgs/LaserScan.msg:
std_msgs/Header header
float32 angle_min
float32 angle_max
float32 angle_increment
float32 time_increment **#it seems the value is below zero or beyond INT_MAX, roscore will throw a runtime_error.**
float32 scan_time
float32 range_min
float32 range_max
float32[] ranges
float32[] intensities

in roscpp_core/rostime/include/ros/impl/duration.h
`
    if (sec64 < std::numeric_limits<int32_t>::min() || sec64 > std::numeric_limits<int32_t>::max())`
`
      throw std::runtime_error("Duration is out of dual 32-bit range")
`

in roscpp_core/rostime/include/ros/impl/time.h
`
      if (sec64 < 0 || sec64 > std::numeric_limits<uint32_t>::max())`
`
        throw std::runtime_error("Time is out of dual 32-bit range");
`

before fix:
image

after fix:
image

### CODE REVIEW

**Comment by easylyou** [comment]
fix #1151 about amcl crash.
It only need a few cycles to check some obvious malformed values, which prevents some crashes from these malformed messages.

```
    // in amcl_node.cpp    laserReceived()
    if(laser_max_range_ > 0.0)
      ldata.range_max = std::min(laser_scan->range_max, (float)laser_max_range_);
    else
      ldata.range_max = laser_scan->range_max

    //ldata.range_max is from laser_scan. It could be any value, such as zero.
```
```
    //in amcl_laser.cpp LikelihoodFieldModel()
double AMCLLaser::LikelihoodFieldModel(AMCLLaserData *data, pf_sample_set_t* set){

      double z_rand_mult = 1.0/data->range_max; //if range_max is zero, z_rand_mult will be inf.

      pz += self->z_rand * z_rand_mult;
      assert(pz <= 1.0);
      assert(pz >= 0.0);
}
```

File: amcl/src/amcl_node.cpp [hunk 1]
```diff
@@ -1292,6 +1292,12 @@ AmclNode::laserReceived(const sensor_msgs::LaserScanConstPtr& laser_scan)
       range_min = std::max(laser_scan->range_min, (float)laser_min_range_);
     else
       range_min = laser_scan->range_min;
+
+    if(ldata.range_max <= 0.0 || range_min < 0.0) {
+      ROS_ERROR("range_max or range_min from laser is negetive! ignore this message.");
```
Comment (mikeferguson) [inline amcl/src/amcl_node.cpp]:
```suggestion
      ROS_ERROR("range_max or range_min from laser is negative! ignore this message.");
```

File: costmap_2d/plugins/obstacle_layer.cpp [hunk 2]
```diff
@@ -297,6 +302,11 @@ void ObstacleLayer::laserScanValidInfCallback(const sensor_msgs::LaserScanConstP
              global_frame_.c_str(), ex.what());
     projector_.projectLaser(message, cloud);
   }
+  catch (std::runtime_error &ex)
+  {
+    ROS_WARN("transformLaserScanToPointCloud error, it seems the message from laser sensor is malformed. Ignore this message. what(): %s", ex.what());
```
Comment (mikeferguson) [inline costmap_2d/plugins/obstacle_layer.cpp]:
```suggestion
    ROS_WARN("transformLaserScanToPointCloud error, it seems the message from laser sensor is malformed. Ignore this laser scan. what(): %s", ex.what());
```

File: costmap_2d/plugins/obstacle_layer.cpp [hunk 3]
```diff
@@ -260,6 +260,11 @@ void ObstacleLayer::laserScanCallback(const sensor_msgs::LaserScanConstPtr& mess
              ex.what());
     projector_.projectLaser(*message, cloud);
   }
+  catch (std::runtime_error &ex)
+  {
+    ROS_WARN("transformLaserScanToPointCloud error, it seems the message from laser sensor is malformed. Ignore this message. what(): %s", ex.what());
```
Comment (mikeferguson) [inline costmap_2d/plugins/obstacle_layer.cpp]:
```suggestion
    ROS_WARN("transformLaserScanToPointCloud error, it seems the message from laser sensor is malformed. Ignore this laser scan. what(): %s", ex.what());
```

**Review by mikeferguson — APPROVED** [review]

**Comment by mikeferguson** [comment]
Just going to wait for CI to complete, then I'll merge this
